version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://evan:Aa123456@host.docker.internal:5432/my_db"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: evan
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: my_db
    volumes:
      - C:/Users/evan0/PycharmProjects/PythonProject/PycharmProjectsOLD/testbot/project-root/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Пробрасываем порт 5432 для доступа к базе данных на хосте
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Используем стандартную bridge-сеть

volumes:
  postgres_data:
